<?php

/**
 * Session bootstrap and server-side identity storage.
 *
 * Ticket99 historically carried identity in a browser cookie named `user` whose
 * value was the raw users.id — unsigned, and trusted on sight. This helper moves
 * that identity server-side into a PHP session, so the browser holds only an
 * opaque session id that the server can invalidate.
 *
 * Native PHP sessions only: the Phase 1 deployment target is a single LAMP host,
 * so no shared session store is introduced.
 */

if (!function_exists('ticket99_request_is_https')) {

/**
 * Decide whether the current request arrived over HTTPS.
 *
 * The forwarded-proto header is honoured because the app is expected to run
 * behind a terminating proxy, where $_SERVER['HTTPS'] is unset even though the
 * client connection was encrypted. Getting this wrong in the safe direction
 * only costs the Secure flag on plain HTTP, which is the correct behaviour.
 */
function ticket99_request_is_https() {

    if (!empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off') {
        return true;
    }

    if (isset($_SERVER['SERVER_PORT']) && (int) $_SERVER['SERVER_PORT'] === 443) {
        return true;
    }

    if (!empty($_SERVER['HTTP_X_FORWARDED_PROTO'])
        && strtolower($_SERVER['HTTP_X_FORWARDED_PROTO']) === 'https') {
        return true;
    }

    return false;
}

}

if (!function_exists('ticket99_session_start')) {

/**
 * Start the helpdesk session with hardened cookie attributes.
 *
 * Every runtime session_start in the application funnels through here so the
 * attributes cannot drift between entry points. Safe to call repeatedly: an
 * already-active session returns immediately.
 *
 * - HttpOnly keeps the session id out of reach of script, which matters while
 *   the render paths are still unescaped.
 * - SameSite=Lax blunts cross-site POSTs ahead of the dedicated CSRF work, and
 *   still permits ordinary top-level navigation into the app.
 * - Secure is set only for HTTPS requests, so local HTTP development keeps
 *   working without a config switch.
 * - use_strict_mode makes PHP reject a session id it did not issue, which
 *   closes session fixation.
 */
function ticket99_session_start() {

    if (session_status() === PHP_SESSION_ACTIVE) {
        return;
    }

    if (headers_sent()) {
        return;
    }

    ini_set('session.use_only_cookies', '1');
    ini_set('session.use_strict_mode', '1');
    ini_set('session.use_trans_sid', '0');

    $params = array(
        'lifetime' => 0,
        'path'     => '/',
        'domain'   => '',
        'secure'   => ticket99_request_is_https(),
        'httponly' => true,
        'samesite' => 'Lax',
    );

    if (PHP_VERSION_ID >= 70300) {
        session_set_cookie_params($params);
    } else {
        // Pre-7.3 has no samesite key; it rides along on the path argument,
        // which is the documented workaround for that runtime.
        session_set_cookie_params(
            $params['lifetime'],
            $params['path'] . '; samesite=' . $params['samesite'],
            $params['domain'],
            $params['secure'],
            $params['httponly']
        );
    }

    session_start();
}

}

if (!function_exists('ticket99_session_set_user_id')) {

/**
 * Record the authenticated user's id in server-side session state.
 *
 * Called only after credentials have been accepted. The session id is
 * regenerated by the caller at that same moment so a pre-authentication session
 * id cannot be replayed as an authenticated one.
 */
function ticket99_session_set_user_id($user_id) {

    ticket99_session_start();

    $_SESSION['ticket99_user_id'] = (int) $user_id;
}

}

if (!function_exists('ticket99_session_user_id')) {

/**
 * Return the authenticated user's id, or null when nobody is signed in.
 *
 * This is the only trustworthy answer to "who is making this request". Callers
 * must not fall back to $_COOKIE['user'], which the browser controls.
 */
function ticket99_session_user_id() {

    ticket99_session_start();

    if (isset($_SESSION['ticket99_user_id']) && (int) $_SESSION['ticket99_user_id'] > 0) {
        return (int) $_SESSION['ticket99_user_id'];
    }

    return null;
}

}

if (!function_exists('ticket99_session_clear_identity')) {

/**
 * Drop the authenticated identity from the session.
 *
 * Only the identity key is removed here; full session destruction on sign-out
 * is handled by the logout path so this stays usable mid-request.
 */
function ticket99_session_clear_identity() {

    ticket99_session_start();

    unset($_SESSION['ticket99_user_id']);
}

}
